"""add frequency, next_pay, semimonthly fields

Revision ID: 2c4c88376851
Revises: 164ca30b3930
Create Date: 2025-08-24 04:52:34.564070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4c88376851'
down_revision = '164ca30b3930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_pay', sa.Date(), nullable=True),
    sa.Column('day_of_month_1', sa.Integer(), nullable=True),
    sa.Column('day_of_month_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bill')
    op.drop_table('income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('next_pay', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('day_of_month_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_month_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('income_pkey'))
    )
    op.create_table('bill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('due_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bill_pkey'))
    )
    op.drop_table('incomes')
    op.drop_table('bills')
    # ### end Alembic commands ###
