"""Initial revision

Revision ID: 3cec62fbb3a2
Revises: 
Create Date: 2025-08-22 18:46:46.431211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cec62fbb3a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_day', sa.Integer(), nullable=False))
        batch_op.drop_column('due_date')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_month_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('day_of_month_2', sa.Integer(), nullable=True))
        batch_op.alter_column('next_pay',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('next_pay',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('day_of_month_2')
        batch_op.drop_column('day_of_month_1')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('due_day')

    # ### end Alembic commands ###
