version: "2.4"        # you can omit “version:” too in modern Compose

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: finapp
      POSTGRES_PASSWORD: finapp
      POSTGRES_DB: finapp
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finapp -d finapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      DATABASE_URL: postgresql://finapp:finapp@db:5432/finapp
      SECRET_KEY: 09b895db084da526db4436053b1ec013a6dacd4fee56dccfce11434dcaaf65b9
      FLASK_APP: src.app:create_app
      FLASK_ENV: development
      DEBUG: '1'
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  db-data:

